# Generated by Django 3.2.4 on 2021-07-29 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Op',
            fields=[
                ('opid', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha Pedido')),
                ('cliente', models.CharField(max_length=50, null=True)),
                ('tipoop', models.CharField(choices=[('Esp/Burb', 'Esp/Burb'), ('Reventa', 'Reventa')], max_length=10)),
                ('fact', models.CharField(choices=[('100%', '100%'), ('0%', '0%'), ('50%', '50%')], default='100%', max_length=5)),
                ('condicion', models.CharField(choices=[('Anticipado', 'Anticipado'), ('Contra Entrega', 'Contra Entrega')], default='Anticipado', max_length=20)),
                ('despacho', models.CharField(choices=[('Retira', 'Retira'), ('En transporte', 'En transporte'), ('Bonificado', 'Bonificado'), ('Camion', 'Camion')], max_length=20)),
                ('vendedor', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estadoop', models.CharField(choices=[('OK', 'OK'), ('DUDA', 'DUDA')], default='DUDA', max_length=4)),
                ('deudaop', models.CharField(choices=[('OK', 'OK'), ('DUDA', 'DUDA')], default='DUDA', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npedido1', models.IntegerField(blank=True, default='0', null=True)),
                ('nfactura1', models.IntegerField(blank=True, default='0', null=True)),
                ('nrecibo1', models.IntegerField(blank=True, default='0', null=True)),
                ('npedido2', models.IntegerField(blank=True, default='0', null=True)),
                ('nfactura2', models.IntegerField(blank=True, default='0', null=True)),
                ('nrecibo2', models.IntegerField(blank=True, default='0', null=True)),
                ('op', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carga.op')),
            ],
        ),
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecharem1', models.DateField(blank=True, default='0', null=True, verbose_name='Fecha remito 1')),
                ('nrem1', models.IntegerField(blank=True, default='0', null=True)),
                ('fecharem2', models.DateField(blank=True, default='0', null=True, verbose_name='Fecha remito 1')),
                ('nrem2', models.IntegerField(blank=True, default='0', null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carga.pedido', to_field='op')),
            ],
        ),
    ]
