# Generated by Django 3.2.4 on 2021-08-25 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('codcli', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo Cliente')),
                ('razsoc', models.CharField(max_length=50, verbose_name='Razon Social')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Op',
            fields=[
                ('opid', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha Pedido')),
                ('tipoop', models.CharField(choices=[('Esp/Burb', 'Esp/Burb'), ('Reventa', 'Reventa')], max_length=10, verbose_name='Tipo OP')),
                ('fact', models.CharField(choices=[('100%', '100%'), ('0%', '0%'), ('50%', '50%')], default='100%', max_length=5, verbose_name='Facturacion %')),
                ('condicion', models.CharField(choices=[('Anticipado', 'Anticipado'), ('Contra Entrega', 'Contra Entrega')], default='Anticipado', max_length=20)),
                ('despacho', models.CharField(choices=[('Retira', 'Retira'), ('En transporte', 'En transporte'), ('Bonificado', 'Bonificado'), ('Camion', 'Camion Faterm')], max_length=20)),
                ('observaciones', models.TextField(blank=True, default=' ', null=True, verbose_name='Observaciones')),
                ('estadoop', models.CharField(choices=[('DUDA', 'DUDA'), ('OK', 'OK')], default='DUDA', max_length=4, verbose_name='Estado OP')),
                ('deudaop', models.CharField(choices=[('DUDA', 'DUDA'), ('OK', 'OK')], default='DUDA', max_length=4, verbose_name='Deuda')),
                ('archivoop', models.FileField(blank=True, null=True, upload_to='archivoop', verbose_name='Archivo OP')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('codvend', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo Vendedor')),
                ('nomvend', models.CharField(max_length=50, verbose_name='Nombre Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('op', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='carga.op')),
                ('proforma1', models.IntegerField(blank=True, default='0', null=True, verbose_name='N° Proforma 1')),
                ('npedido1', models.IntegerField(blank=True, default='0', null=True, verbose_name='N° Pedido 1')),
                ('nfactura1', models.IntegerField(blank=True, default='0', null=True, verbose_name='N° Factura 1')),
                ('nrecibo1', models.IntegerField(blank=True, default='0', null=True, verbose_name='N° Recibo 1')),
                ('proforma2', models.IntegerField(blank=True, default='0', null=True, verbose_name='N° Proforma 2')),
                ('npedido2', models.IntegerField(blank=True, default='0', null=True, verbose_name='N° Pedido 2')),
                ('nfactura2', models.IntegerField(blank=True, default='0', null=True, verbose_name='N° Factura 2')),
                ('nrecibo2', models.IntegerField(blank=True, default='0', null=True, verbose_name='N° Recibo 2')),
            ],
        ),
        migrations.AddField(
            model_name='op',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.vendedores'),
        ),
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecharem1', models.DateField(blank=True, default='2021-01-01', null=True, verbose_name='Fecha remito 1')),
                ('nrem1', models.IntegerField(blank=True, default='0', null=True, verbose_name='N° Remito 1')),
                ('rem1', models.FileField(blank=True, null=True, upload_to='remito1', verbose_name='Remito 1')),
                ('fecharem2', models.DateField(blank=True, default='2021-01-01', null=True, verbose_name='Fecha remito 2')),
                ('nrem2', models.IntegerField(blank=True, default='0', null=True, verbose_name='N° Remito 2')),
                ('rem2', models.FileField(blank=True, null=True, upload_to='remito2', verbose_name='Remito 2')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carga.pedido')),
            ],
        ),
    ]
