# Generated by Django 3.2.4 on 2021-08-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0005_auto_20210813_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='remito',
            name='rem1',
            field=models.FileField(blank=True, null=True, upload_to='remito1', verbose_name='Remito 1'),
        ),
        migrations.AddField(
            model_name='remito',
            name='rem2',
            field=models.FileField(blank=True, null=True, upload_to='remito2', verbose_name='Remito 2'),
        ),
    ]
