# Generated by Django 3.2.4 on 2021-08-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0006_auto_20210815_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='proforma1',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° Proforma 1'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='proforma2',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° Proforma 2'),
        ),
        migrations.AlterField(
            model_name='op',
            name='despacho',
            field=models.CharField(choices=[('Retira', 'Retira'), ('En transporte', 'En transporte'), ('Bonificado', 'Bonificado'), ('Camion', 'Camion Faterm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='op',
            name='deudaop',
            field=models.CharField(choices=[('DUDA', 'DUDA'), ('OK', 'OK')], default='DUDA', max_length=4, verbose_name='Deuda'),
        ),
        migrations.AlterField(
            model_name='op',
            name='estadoop',
            field=models.CharField(choices=[('DUDA', 'DUDA'), ('OK', 'OK')], default='DUDA', max_length=4, verbose_name='Estado OP'),
        ),
    ]
